APP_DIRECTORY optional
Updated to make database and app dir backups optional

diff --git a/backup b/backup
--- a/backup
+++ b/backup
@@ -2,6 +2,8 @@
 
 set -e
 
+FINISHED=false
+
 cleanup() {
   echo "Cleanup backup older than $CLEANUP_OLDER_THAN days"
   toberemove=$(find /backup/ -type f -not -name ".*" -mtime +$CLEANUP_OLDER_THAN | wc -l)
@@ -9,18 +11,23 @@ cleanup() {
   find /backup/ -type f -not -name ".*" -mtime +$CLEANUP_OLDER_THAN -exec rm {} \;
 }
 
-if [ -z "${MYSQL_HOST}" ]; then echo "Error: MYSQL_HOST not set"; echo "Finished: FAILURE"; exit 1; fi
-if [ -z "${MYSQL_USER}" ]; then echo "Error: MYSQL_USER not set"; echo "Finished: FAILURE"; exit 1; fi
-if [ -z "${MYSQL_DATABASE}" ]; then echo "Error: MYSQL_DATABASE not set"; echo "Finished: FAILURE"; exit 1; fi
-if [ -z "${MYSQL_PASSWORD_FILE}" ]; then echo "Error: MYSQL_PASSWORD_FILE not set"; echo "Finished: FAILURE"; exit 1; fi
-if [ -z "${APP_DIRECTORY}" ]; then echo "Error: APP_DIRECTORY not set"; echo "Finished: FAILURE"; exit 1; fi
-
 if [ -n "$CLEANUP_OLDER_THAN" ]; then cleanup;  fi
 
-echo 'creating backup archive of /var/www/html'
-tar -zpc --directory="${APP_DIRECTORY}" --file="/backup/backup_`date '+%Y%m%d'`.tar.gz" "./"
+if [ -n "${APP_DIRECTORY}" ]; then
+  echo 'creating backup archive of ${APP_DIRECTORY}'
+  tar -zpc --directory="${APP_DIRECTORY}" --file="/backup/backup_`date '+%Y%m%d'`.tar.gz" "./"
+  FINISHED=true
+fi
 
-echo 'creating database dump'
-mysqldump --host="${MYSQL_HOST}" --add-drop-table --user="${MYSQL_USER}" --password="$(cat ${MYSQL_PASSWORD_FILE})" "${MYSQL_DATABASE}" | bzip2 -c > "/backup/backup_`date '+%Y%m%d'`.sql.bz2"
+if [ -n "${MYSQL_HOST}" -a -n "${MYSQL_USER}" -a -n "${MYSQL_DATABASE}" -a -n "${MYSQL_PASSWORD_FILE}" ]; then
+  echo 'creating database dump'
+  mysqldump --host="${MYSQL_HOST}" --add-drop-table --user="${MYSQL_USER}" --password="$(cat ${MYSQL_PASSWORD_FILE})" "${MYSQL_DATABASE}" | bzip2 -c > "/backup/backup_`date '+%Y%m%d'`.sql.bz2"
+  FINISHED=true
+fi
+
+if [ "$FINISHED" == "false" ]; then
+  echo "ERROR: the container isnt configured correctly, neither APP_DIRECTORY or MYSQL were backed up."
+  exit 1
+fi
 
 echo 'Finished: SUCCESS'
